language: rust

rust:
  - stable

cache: cargo

script:
  - cargo build --verbose --all
  - cargo test --verbose -- --test-threads=1

services:
  - docker

before_script:
  - ./bin/setup-and-wait.sh

after_success:
  - ./bin/smoketest.sh
