language: rust

rust:
  - stable

cache: cargo

script:
  - cargo build --verbose --all
  - cargo test --verbose -- --test-threads=1

services:
  - docker

before_script:
  - docker-compose up
  - sleep 10 #TODO: poll ES using nc or curl
