language: rust
rust:
- stable
cache: cargo
script:
- if [ -z $TRAVIS_TAG ]; then
    cargo build --all
  fi
- if [ -z $TRAVIS_TAG ]; then
    cargo test -- --test-threads=1
  fi
- if [ -z $TRAVIS_TAG ]; then
  ./bin/smoketest.sh
  fi
matrix:
  include:
  - name: With Elasticsearch 6xx
    env: ES_IMAGE=elasticsearch:2.4.6
  - name: With Elasticsearch 2xx
    env: ES_IMAGE=docker.elastic.co/elasticsearch/elasticsearch:6.5.0
services:
- docker
before_script:
- "./bin/setup-and-wait.sh"
deploy:
- provider: releases
  api_key:
    secure: GITHUB_TOKEN
  file: target/x86_64-unknown-linux-musl/release/rmqfwd
  skip_cleanup: true
  on:
    tags: true
- provider: cargo
  token: CARGO_TOKEN
  on:
    tags: true
before_deploy:
- "./bin/build.sh"
env:
  global:
  - secure: GnAbB3WK0bxR5SeXOZDJZSbs06RB87FGdBDt0G696qyE+7piGFUKQAxyujq9b0T5aefRw8fJbfx1tEG6Kc2ro8V3CwxUOjxamr0myueZf9LnxsczSsWXpF0Y7W2c58NVPoXtl1PIcf5nye748XGRLMFDD5WZ7tu0c+I+6260cC2nW1GuZIkpY1SfjhHBFMOi8o+6aKigjJK01iIO0fOD+/bItRrbYRuQ8yeA4MiD9KhqcTQlj9H1X+3dnhoS3fHG9ckc0cF6r9KLWzA1efNcWhWwFO0mIW2flN/yBj/gX+RsO+g9sSZsrlzYpX/u26EGkCrrbkmGxvyptwK/wHJYPXIaNYv4jR7owuMkY/+bV3Mw7RNopgkgp5ffpaCyyId1ojhavGzfRqxabphH2YDe/9WgGgqWg46gH0SXyqOOGivYzZiIKnQh7w655qMGRe/UBQ+Z1hzz+deUiW6iSaPK9+ygFsIfAt4UfFeJkvsmNmZFRkFwO8nWDG/73Qh6xQtb61U0w52Z0fQLUwlWTPYLssc+PJoBs9JxuxzaL9drcvGtHaghJB7ct00aFhkgFbhJj1eUUuocRsS/DqF0LEPMqzBKxpUXY6O4cfVqMaoAcvgI8uU0mbzwFA1ZMo2pQ4WHYBkRfYp3T6iEhag6tK5ACIhihFRr1ngnFPaNdWGu+gQ=
  - secure: wJRhJPMhWoNciF/vFABc4EARE9w3f0p7UWYx35UHLqj58tfDHXetm/hyiL6TgMYSW5Tub1X4mbqRFFMoojO1TkWHMJC3QHQlGrGtOd3SbRBBZ27B78dXt10KtPZDz1kl0nNhuVMLvgLOKmbA9HqnWeyWI5MZAtX+Vv5r8r9hBcU/DVeCK/vd08iKxWmb3Q4Sbf7HXWFKv54b+j6MfraGa0jzH8I1aIbIYqSFFzwNsClgkttwN8FXnd1t93VqiTYi57L6ep/tS+yAg9KDTHScTLd5AYaTDV5aHMC1eMsjrS5pi2PiOVKD8oSoe1EIm4+phviSbfRYBvMAZEnA/0Clc6Wm79/2E/+yJm4xXwW//0x1g9tPR2mtisUjG3qmT48aqRCkOq+2wYft/7n2+EqjwQ8fwnYElIcyy5lsVJEQcDnHCuYT145234eXLPwCEzJPfi7j9pgR0QceyxpR2W0W6tzC+4erpmOjAhvGwBEbJ8egXa1p8OyP8IWumc+Nwi1aiXI6hBOezwqz03dRW33pwsNBnOurLr6DsRFEpqU1RyJRitNy+Nniz944Bqpg/f8oPXuBsVyiYenNUqLv8GfevoLiwKLTF1isdT8nRT7uJBPz0Wnsw+KNMRBnVqkwjtfVmDduYtpbmleeqGnHne+bsvaRYtMjjPgvdx7xMjw+naM=
