[package]
name = "rmqfwd"
version = "0.1.0"
authors = ["andrfior <andrea.giulio.fiore@gmail.com>"]

[dependencies]
lapin-futures = "^0.13"
serde = "1.0"
serde_derive = "1.0"
serde_json = "1.0"
tokio = "0.1"
futures = "0.1"
log = "0.4"
