# this is only intended for running the application locally, as integration tests will automatically spawn docker
# containers and potentially teardown the ones run via docker-compose

version: '2'
services:
  elasticsearch: 
    image: "${ES_IMAGE}"
    ports:
         - 9200:9200 
         - 9300:9300 
    environment:
      discovery.type: single-node
  rabbit:
    image: afiore/rabbitmq
    environment:
      HAB_RABBITMQ: '{"loopback_users": {"guest": false}}'
    ports:
         - 5672:5672
         - 15672:15672
#        - 9631:9631 # Habitat supervisor
    hostname: "messaging"
