apiVersion: v1
kind: Service
metadata:
  name: es
  labels:
    service: elasticsearch
spec:
  selector:
    service: elasticsearch
  ports:
  - name: transport
    port: 9300
    protocol: TCP
  clusterIP: None
