apiVersion: apps/v1beta1
kind: StatefulSet
metadata:
  name: rmq
spec:
  serviceName: rmq
  replicas: 3
  volumeClaimTemplates:
  - metadata:
      name: rmq
    spec:
      accessModes: ["ReadWriteOnce"]
      storageClassName: fast
      resources:
        requests:
          storage: 1Gi
  template:
    metadata:
      labels:
        app: rmq
    spec:
      containers:
      - name: rmq
        image: rabbitmq-cluster:3.6.13
        lifecycle:
          preStop:
            exec:
              command: ["rabbitmqctl", "stop"]

        livenessProbe:
          initialDelaySeconds: 10
          timeoutSeconds: 5
          failureThreshold: 30
          exec:
            command: ["rabbitmqctl", "node_health_check"]

        readinessProbe:
          initialDelaySeconds: 10
          timeoutSeconds: 5
          periodSeconds: 1
          failureThreshold: 10
          exec:
            command: ["rabbitmqctl", "node_health_check"]

        ports:
        - containerPort: 4369
        - containerPort: 5672
        - containerPort: 15672
        - containerPort: 25672

        volumeMounts:
          - mountPath: /var/lib/rabbitmq
            name: rmq

        env:
          - name: CLUSTERED
            value: "true"
          - name: CLUSTER_WITH
            value: "rmq-0"
          - name: RABBITMQ_SERVICE_DOMAIN
            value: "rmq.default.svc.cluster.local"
          - name: RABBITMQ_USERNAME
            value: "test"
          - name: RABBITMQ_PASSWORD
            value: "testpass"
          - name: RABBITMQ_VHOST
            value: "/"
          - name: RABBITMQ_VHOST
            value: "/"
          - name: RABBITMQ_ERLANG_COOKIE
            value: "584ee2e9-99ba-4736-9e4d-f12273f171c6"
      - name: fwd
        image: rmqfwd:latest
        imagePullPolicy: IfNotPresent
        args: 
        - "trace" 
        - "--es-major-version"
        - "6" 
        - "--rmq-creds"
        - "test:testpass" 
        - "--rmq-host"
        - "rmq-0.rmq.default.svc.cluster.local" 
        - "--es-base-url"
        - "http://elasticsearch-0.es.default.svc.cluster.local:9200"
        env:
          - name: RUST_LOG
            value: "rmqfwd=DEBUG"
          - name: RUST_BACKTRACE
            value: "1"

---
kind: StorageClass
apiVersion: storage.k8s.io/v1
metadata:
  name: fast
provisioner: k8s.io/minikube-hostpath
parameters:
  type: pd-ssd
